apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-secret.yaml
  - postgresql-deployment.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
