apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-argocd-demo
bases:
  - ../../base
images:
  - name: image-registry.openshift-image-registry.svc:5000/NAMESPACE/shipper-onboarding-api
    newName: image-registry.openshift-image-registry.svc:5000/tekton-argocd-demo/shipper-onboarding-api
    newTag: 6088b3024994aac7572e54b25895b5886e0961fa
commonLabels:
  environment: dev
