apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-argocd-demo
bases:
  - ../../base
images:
  - name: image-registry.openshift-image-registry.svc:5000/NAMESPACE/shipper-onboarding-api
    newName: image-registry.openshift-image-registry.svc:5000/tekton-argocd-demo/shipper-onboarding-api
    newTag: 0415a56a9075857436f68c7c1f549a9162cfbb1a
commonLabels:
  environment: dev
